[package]
name = "crypto-keep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"] #编译wasm文件的选项

[dependencies]
near-sdk = "4.1.1"
serde = "1.0"
serde_derive = "1.0"